// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoSmith.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Smith.Proto.ProtoSmith {
  public static partial class Bot
  {
    static readonly string __ServiceName = "smith.proto.protosmith.Bot";

    static readonly grpc::Marshaller<global::Smith.Proto.ProtoSmith.AskRequest> __Marshaller_AskRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Smith.Proto.ProtoSmith.AskRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Smith.Proto.ProtoSmith.AskResponse> __Marshaller_AskResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Smith.Proto.ProtoSmith.AskResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Smith.Proto.ProtoSmith.AskRequest, global::Smith.Proto.ProtoSmith.AskResponse> __Method_Ask = new grpc::Method<global::Smith.Proto.ProtoSmith.AskRequest, global::Smith.Proto.ProtoSmith.AskResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ask",
        __Marshaller_AskRequest,
        __Marshaller_AskResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Smith.Proto.ProtoSmith.ProtoSmithReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Bot</summary>
    public abstract partial class BotBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Smith.Proto.ProtoSmith.AskResponse> Ask(global::Smith.Proto.ProtoSmith.AskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Bot</summary>
    public partial class BotClient : grpc::ClientBase<BotClient>
    {
      /// <summary>Creates a new client for Bot</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BotClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Bot that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BotClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BotClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BotClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Smith.Proto.ProtoSmith.AskResponse Ask(global::Smith.Proto.ProtoSmith.AskRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Ask(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Smith.Proto.ProtoSmith.AskResponse Ask(global::Smith.Proto.ProtoSmith.AskRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ask, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Smith.Proto.ProtoSmith.AskResponse> AskAsync(global::Smith.Proto.ProtoSmith.AskRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AskAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Smith.Proto.ProtoSmith.AskResponse> AskAsync(global::Smith.Proto.ProtoSmith.AskRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ask, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BotClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BotClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BotBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ask, serviceImpl.Ask).Build();
    }

  }
}
#endregion
